version: "0.5"

processes:
  firebase-emulators:
    description: This process runs the local firebase emulators used in the project.
    command: firebase emulators:start --project demo-bdt-dev --only auth,storage,firestore --import ./emulator-data --export-on-exit
    ready_log_line: "All emulators ready!"
  library-api:
    description: This process runs the library-api in dev mode on port ${QUARKUS_HTTP_PORT}.
    command: quarkus dev -Ddebug=false
    working_dir: library-api/
    environment:
      - "QUARKUS_CONSOLE_COLOR=true"
    ready_log_line: "Listening on: http://localhost:"
  sync-library-metadata:
    description: Sync library check metadata from library-api to Firebase Storage
    command: ./bin/library/sync-metadata
    depends_on:
      library-api:
        condition: process_log_ready
      firebase-emulators:
        condition: process_log_ready
    availability:
      restart: on_failure
      max_restarts: 1
  builder-api:
    description: This process runs the builder-api in dev mode on port ${QUARKUS_HTTP_PORT}.
    command: quarkus dev -Ddebug=5005
    working_dir: builder-api/
    environment:
      - "QUARKUS_CONSOLE_COLOR=true"
    ready_log_line: "Listening on: http://localhost:"
    depends_on:
      sync-library-metadata:
        condition: process_completed_successfully
      firebase-emulators:
        condition: process_log_ready
  builder-frontend:
    description: This process runs the builder-frontend in dev mode.
    command: npm run dev -- --host
    working_dir: builder-frontend/
    depends_on:
      builder-api:
        condition: process_log_ready
